package com.training.java.entities.enums;

public enum StatesOfIndia {

        Andhra_Pradesh,
        Arunachal_Pradesh,
        Assam,
        Bihar,
        Chhattisgarh,
        Goa,
        Gujarat,
        Haryana,
        Himachal_Pradesh,
        Jharkhand,
        Karnataka,
        Kerala,
        Madhya_Pradesh,
        Maharashtra,
        Manipur,
        Meghalaya,
        Mizoram,
        Nagaland,
        Odisha,
        Punjab,
        Rajasthan,
        Sikkim,
        Tamil_Nadu,
        Telangana,
        Tripura,
        Uttar_Pradesh,
        Uttarakhand,
        West_Bengal,
        Andaman_and_Nicobar_Islands,
        Chandigarh,
        Dadra_and_Nagar_Haveli,
        Daman_and_Diu,
        Delhi,
        Lakshadweep,
        Puducherry
    
}
